import {
  Binary,
  Braces,
  Clock3,
  Code2,
  Diff,
  FileCode2,
  FileText,
  Fingerprint,
  Hash,
  KeyRound,
  Link,
  Pilcrow,
  ShieldCheck,
  Sparkles,
  TextCursorInput,
} from "lucide-react";
import type { ToolCategory } from "./tool.categories";
import type { ToolDefinition } from "./tool.definition";

export const toolRegistry: ToolDefinition[] = [
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    category: "Editors",
    description: "Edit Markdown and preview rendered output side by side.",
    keywords: ["markdown", "preview", "editor", "html"],
    icon: FileText,
    persist: true,
    route: "/tools/markdown-preview",
    status: "available",
  },
  {
    id: "html-preview",
    name: "HTML Preview",
    category: "Editors",
    description: "Write HTML and inspect a sandboxed live preview.",
    keywords: ["html", "preview", "sandbox", "iframe"],
    icon: FileCode2,
    persist: true,
    route: "/tools/html-preview",
    status: "planned",
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    category: "Editors",
    description: "Compare two text inputs with focused diff controls.",
    keywords: ["diff", "compare", "text", "changes"],
    icon: Diff,
    persist: true,
    route: "/tools/diff-checker",
    status: "planned",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    category: "Data",
    description: "Format, validate, and inspect JSON payloads.",
    keywords: ["json", "format", "validate", "beautify"],
    icon: Braces,
    persist: true,
    route: "/tools/json-formatter",
    status: "planned",
  },
  {
    id: "json-yaml",
    name: "JSON YAML Converter",
    category: "Data",
    description: "Convert between JSON and YAML for config workflows.",
    keywords: ["json", "yaml", "convert", "config"],
    icon: Code2,
    persist: true,
    route: "/tools/json-yaml",
    status: "planned",
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    category: "Data",
    description: "Decode JWT headers and payloads without sending tokens away.",
    keywords: ["jwt", "token", "decode", "claims"],
    icon: ShieldCheck,
    persist: false,
    route: "/tools/jwt-decoder",
    status: "planned",
  },
  {
    id: "base64",
    name: "Base64",
    category: "Encoding",
    description: "Encode and decode Base64 strings locally.",
    keywords: ["base64", "encode", "decode"],
    icon: Binary,
    persist: false,
    route: "/tools/base64",
    status: "planned",
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    category: "Encoding",
    description: "Encode and decode URL components safely.",
    keywords: ["url", "encode", "decode", "uri"],
    icon: Link,
    persist: false,
    route: "/tools/url-encoder",
    status: "planned",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    category: "Crypto",
    description: "Generate common hashes from local text input.",
    keywords: ["hash", "sha", "sha256", "sha512"],
    icon: Hash,
    persist: false,
    route: "/tools/hash-generator",
    status: "planned",
  },
  {
    id: "password-generator",
    name: "Password Generator",
    category: "Crypto",
    description: "Generate strong local passwords with configurable rules.",
    keywords: ["password", "generator", "random", "security"],
    icon: KeyRound,
    persist: false,
    route: "/tools/password-generator",
    status: "planned",
  },
  {
    id: "uuid",
    name: "UUID Generator",
    category: "Utilities",
    description: "Generate single or batch UUID values.",
    keywords: ["uuid", "guid", "random"],
    icon: Fingerprint,
    persist: false,
    route: "/tools/uuid",
    status: "planned",
  },
  {
    id: "timestamp",
    name: "Timestamp Converter",
    category: "Utilities",
    description: "Convert Unix timestamps and readable dates.",
    keywords: ["timestamp", "date", "time", "unix"],
    icon: Clock3,
    persist: false,
    route: "/tools/timestamp",
    status: "planned",
  },
  {
    id: "case-converter",
    name: "Case Converter",
    category: "Utilities",
    description: "Convert text between common naming conventions.",
    keywords: ["case", "camel", "snake", "kebab", "pascal"],
    icon: TextCursorInput,
    persist: false,
    route: "/tools/case-converter",
    status: "planned",
  },
  {
    id: "slugify",
    name: "Slugify",
    category: "Utilities",
    description: "Create clean URL slugs from human-readable text.",
    keywords: ["slug", "url", "text"],
    icon: Pilcrow,
    persist: false,
    route: "/tools/slugify",
    status: "planned",
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    category: "Utilities",
    description: "Test regular expressions against sample input.",
    keywords: ["regex", "regexp", "pattern", "match"],
    icon: Sparkles,
    persist: true,
    route: "/tools/regex-tester",
    status: "planned",
  },
];

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return toolRegistry.filter((tool) => tool.category === category);
}

export function getToolById(toolId: string): ToolDefinition | undefined {
  return toolRegistry.find((tool) => tool.id === toolId);
}
